version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/2.sql"